### ISSUE TITLE
NPM Package Missing

### ISSUE THREAD

**Issue by iChaosren** [curious-machines/gp-data-transformer#39]
Hi,

My project is using the `kld-intersections` package and for whatever reason when I attempted to `yarn` it says the package `gp-data-transformer` does not exist...
After more investigation, it seems like the package was removed/hidden from npmjs.com...

[https://www.npmjs.com/package/gp-data-transformer](https://www.npmjs.com/package/gp-data-transformer)

I get a 404:

![image](https://user-images.githubusercontent.com/783885/88911806-b0038180-d25e-11ea-9a68-2dcf9b775125.png)

**Comment by thelonious** [comment]
Hi @iChaosren,

Can you update to kld-intersections 0.7.0? It drops this dependency and fixes some arc-related bugs.

**Comment by iChaosren** [comment]
Thanks!
Didn't know they removed the dependency...
Still weird that the package was removed from `npmjs`.
